services:
  backend:
    build:
      context: ./Backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "sleep 15 && npm install && npm run migrate && npm start"

  frontend:
    build:
      context: ./Frontend
    env_file:
      - ./Frontend/.env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tiapartners
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: