name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -ppassword"
          --health-interval=5s --health-timeout=5s --health-retries=30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install frontend dependencies
        working-directory: Frontend
        run: npm install

      - name: Run Frontend
        working-directory: Frontend
        run: npm run dev

      - name: Install backend dependencies
        working-directory: Backend
        run: npm install

      - name: Setup database
        working-directory: Backend
        env:
          NODE_ENV: development
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: app_test
        run: npm run migrate

      - name: Run backend tests
        working-directory: Backend
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: app_test
          JWT_SECRET: thisisaplaceholderjwtsecretfordevelopment
        run: npm run test
